<a href="https://colab.research.google.com/github/bongminyoon/bong/blob/main/tripipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!wget -q URL

In [3]:
import pandas as pd

In [5]:
df_place = pd.read_csv('/content/tn_visit_area_info_방문지정보_A.csv')

df_place

,VISIT_AREA_ID,TRAVEL_ID,VISIT_ORDER,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,LOTNO_ADDR,X_COORD,Y_COORD,...,POI_NM,RESIDENCE_TIME_MIN,VISIT_AREA_TYPE_CD,REVISIT_YN,VISIT_CHC_REASON_CD,LODGING_TYPE_CD,DGSTFN,REVISIT_INTENTION,RCMDTN_INTENTION,SGG_CD
0,2210300006,a_a015688,5,프로방스마을,2022-10-30,2022-10-30,경기 파주시 탄현면 새오리로 77,경기 파주시 탄현면 성동리 82-1,126.685239,37.790405,...,NaN,60.0,7,Y,9.0,NaN,4.0,4.0,4.0,NaN
1,2208050001,a_a000164,1,친구/친지집,2022-08-05,2022-08-05,NaN,경기도 안산시 단원구 와동,NaN,NaN,...,NaN,NaN,22,NaN,NaN,NaN,NaN,NaN,NaN,41273.0
2,2210030002,a_a004293,2,병점역 1호선,2022-10-03,2022-10-03,경기 화성시 떡전골로 97,경기 화성시 진안동 824-1,127.033200,37.206753,...,병점역,30.0,9,Y,6.0,NaN,4.0,5.0,5.0,NaN
3,2208200003,a_a000491,12,더현대서울,2022-08-20,2022-08-20,서울 영등포구 여의대로 108,서울 영등포구 여의도동 22,126.928446,37.525872,...,NaN,180.0,4,N,2.0,NaN,5.0,5.0,5.0,NaN
4,2208110007,a_a000172,13,강릉중앙시장,2022-08-11,2022-08-11,강원 강릉시 금성로 21,강원 강릉시 성남동 50,128.898624,37.754025,...,신흥수산,30.0,4,N,1.0,NaN,4.0,4.0,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30149,2210220005,a_a008553,5,집,2022-10-22,2022-10-23,NaN,NaN,NaN,NaN,...,NaN,300.0,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30150,2208280003,a_a001505,6,카페아쁠뤼스,2022-08-28,2022-08-28,경기 가평군 청평면 신청평로 107,경기 가평군 청평면 대성리 3-5,127.406939,37.728238,...,NaN,90.0,11,N,9.0,NaN,5.0,4.0,4.0,NaN
30151,2210290005,a_a013660,4,국립중앙박물관,2022-10-29,2022-10-29,서울 용산구 서빙고로 137,서울 용산구 용산동6가 168-6,126.980203,37.523847,...,국립중앙박물관,30.0,2,N,10.0,NaN,5.0,5.0,5.0,NaN
30152,2208060008,a_a000019,7,송도달빛축제공원,2022-08-06,2022-08-06,인천 연수구 센트럴로 350,인천 연수구 송도동 26-1,126.634896,37.407218,...,NaN,60.0,8,N,9.0,NaN,4.0,4.0,4.0,NaN
30153,2209060002,a_a000567,2,콩카페 롯데백화점 잠실점,2022-09-06,2022-09-06,서울 송파구 올림픽로 240,서울 송파구 잠실동 40-1,127.098572,37.511906,...,롯데월드어드벤처,0.0,11,N,9.0,NaN,3.0,2.0,2.0,NaN

In [6]:
df_travel = pd.read_csv('/content/tn_travel_여행_A.csv')

df_travel

,TRAVEL_ID,TRAVEL_NM,TRAVELER_ID,TRAVEL_PURPOSE,TRAVEL_START_YMD,TRAVEL_END_YMD,MVMN_NM,TRAVEL_PERSONA,TRAVEL_MISSION,TRAVEL_MISSION_CHECK
0,a_a014262,A03,a014262,1;11;2;22;,2022-10-29,2022-10-30,자가용,NaN,1;11;2;22;,2;1;22
1,a_a006728,A03,a006728,21;24;5;22;26;27;,2022-10-10,2022-10-11,자가용,NaN,21;24;5;22;26;27;,6;1;22
2,a_a015745,A02,a015745,1;2;6;,2022-10-31,2022-11-03,대중교통 등,NaN,1;2;6;,13;3;28
3,a_a010544,A03,a010544,21;22;24;26;,2022-11-01,2022-11-02,자가용,NaN,21;22;24;26;,1;22;26
4,a_a012058,A03,a012058,1;4;10;12;21;22;26;,2022-11-05,2022-11-06,대중교통 등,수도권 외 거주 39세 이하 커플,1;4;10;12;21;22;26;,1;21;22
...,...,...,...,...,...,...,...,...,...,...
3195,a_a008457,A01,a008457,1;23;24;4;6;,2022-10-16,2022-10-18,대중교통 등,NaN,1;23;24;4;6;,6;23;4
3196,a_a007638,A03,a007638,1;21;22;,2022-10-23,2022-10-24,NaN,수도권 거주 39세 이하 부부,1;21;22;,1;22;4
3197,a_a002111,A01,a002111,4;6;,2022-09-20,2022-09-22,대중교통 등,NaN,4;6;,6;4;21
3198,a_a007634,A03,a007634,21;22;4;,2022-10-22,2022-10-23,NaN,수도권 거주 39세 이하 커플,21;22;4;,1;21;4
3199,a_a007716,A03,a007716,28;,2022-10-22,2022-10-23,자가용,NaN,28;,28;3;1

In [8]:
df_traveler = pd.read_csv('/content/tn_traveller_master_여행객 Master_A.csv')

df_traveler

,TRAVELER_ID,RESIDENCE_SGG_CD,GENDER,AGE_GRP,EDU_NM,EDU_FNSH_SE,MARR_STTS,FAMILY_MEMB,JOB_NM,JOB_ETC,...,TRAVEL_STYL_7,TRAVEL_STYL_8,TRAVEL_STATUS_RESIDENCE,TRAVEL_STATUS_DESTINATION,TRAVEL_STATUS_ACCOMPANY,TRAVEL_STATUS_YMD,TRAVEL_MOTIVE_1,TRAVEL_MOTIVE_2,TRAVEL_MOTIVE_3,TRAVEL_COMPANIONS_NUM
0,b015583,41,여,20,6,1.0,1.0,5,3.0,NaN,...,1,7,경기도,충남,2인 여행(가족 외),2022-10-29~2022-10-30,1,NaN,NaN,1
1,a001105,30,남,30,6,1.0,1.0,2,3.0,NaN,...,6,5,대전광역시,경기,3인 이상 여행(가족 외),2022-09-03~2022-09-04,3,NaN,NaN,7
2,a001673,41,여,30,4,1.0,2.0,3,NaN,1.0,...,2,7,경기도,서울,자녀 동반 여행,2022-09-18~2022-09-19,10,7.0,1.0,2
3,a017690,41,여,30,6,1.0,1.0,3,3.0,NaN,...,4,5,경기도,서울,3인 이상 여행(가족 외),2022-11-12~2022-11-12,3,1.0,2.0,3
4,c006666,28,여,30,6,1.0,1.0,3,13.0,NaN,...,5,5,인천광역시,경기,나홀로 여행,2022-10-18~2022-10-18,1,7.0,2.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,b006351,43,여,30,6,1.0,1.0,4,4.0,NaN,...,2,6,충청북도,강원,나홀로 여행,2022-10-07~2022-10-07,1,2.0,5.0,0
3196,a000318,29,남,20,6,1.0,1.0,4,3.0,NaN,...,1,1,광주광역시,경기,3인 이상 여행(가족 외),2022-08-18~2022-08-19,3,2.0,6.0,19
3197,a000787,48,남,30,6,1.0,1.0,4,3.0,NaN,...,2,6,경상남도,서울,나홀로 여행,2022-08-25~2022-08-27,1,4.0,5.0,1
3198,b011659,41,여,40,7,1.0,2.0,3,1.0,NaN,...,6,2,경기도,강원,자녀 동반 여행,2022-11-05~2022-11-05,6,3.0,2.0,2
3199,a008435,11,남,20,6,1.0,1.0,1,7.0,NaN,...,2,7,서울특별시,경기,나홀로 여행,2022-10-15~2022-10-15,6,5.0,1.0,0

In [9]:
df = pd.merge(df_place, df_travel, on='TRAVEL_ID', how='left')
df = pd.merge(df, df_traveler, on='TRAVELER_ID', how='left')

df

,VISIT_AREA_ID,TRAVEL_ID,VISIT_ORDER,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,LOTNO_ADDR,X_COORD,Y_COORD,...,TRAVEL_STYL_7,TRAVEL_STYL_8,TRAVEL_STATUS_RESIDENCE,TRAVEL_STATUS_DESTINATION,TRAVEL_STATUS_ACCOMPANY,TRAVEL_STATUS_YMD,TRAVEL_MOTIVE_1,TRAVEL_MOTIVE_2,TRAVEL_MOTIVE_3,TRAVEL_COMPANIONS_NUM
0,2210300006,a_a015688,5,프로방스마을,2022-10-30,2022-10-30,경기 파주시 탄현면 새오리로 77,경기 파주시 탄현면 성동리 82-1,126.685239,37.790405,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0
1,2208050001,a_a000164,1,친구/친지집,2022-08-05,2022-08-05,NaN,경기도 안산시 단원구 와동,NaN,NaN,...,3.0,5.0,경기도,경기,2인 여행(가족 외),2022-08-05~2022-08-06,3.0,2.0,1.0,1.0
2,2210030002,a_a004293,2,병점역 1호선,2022-10-03,2022-10-03,경기 화성시 떡전골로 97,경기 화성시 진안동 824-1,127.033200,37.206753,...,7.0,2.0,경기도,경기,나홀로 여행,2022-10-03~2022-10-03,6.0,2.0,1.0,0.0
3,2208200003,a_a000491,12,더현대서울,2022-08-20,2022-08-20,서울 영등포구 여의대로 108,서울 영등포구 여의도동 22,126.928446,37.525872,...,5.0,7.0,울산광역시,서울,2인 가족 여행,2022-08-19~2022-08-20,1.0,3.0,7.0,1.0
4,2208110007,a_a000172,13,강릉중앙시장,2022-08-11,2022-08-11,강원 강릉시 금성로 21,강원 강릉시 성남동 50,128.898624,37.754025,...,2.0,4.0,광주광역시,서울,나홀로 여행,2022-08-10~2022-08-13,1.0,7.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30149,2210220005,a_a008553,5,집,2022-10-22,2022-10-23,NaN,NaN,NaN,NaN,...,6.0,3.0,서울특별시,경기,나홀로 여행,2022-10-22~2022-10-22,2.0,1.0,NaN,0.0
30150,2208280003,a_a001505,6,카페아쁠뤼스,2022-08-28,2022-08-28,경기 가평군 청평면 신청평로 107,경기 가평군 청평면 대성리 3-5,127.406939,37.728238,...,5.0,4.0,서울특별시,경기,3인 이상 여행(가족 외),2022-08-27~2022-08-28,1.0,3.0,7.0,7.0
30151,2210290005,a_a013660,4,국립중앙박물관,2022-10-29,2022-10-29,서울 용산구 서빙고로 137,서울 용산구 용산동6가 168-6,126.980203,37.523847,...,5.0,6.0,경기도,서울,나홀로 여행,2022-10-29~2022-10-30,1.0,7.0,8.0,0.0
30152,2208060008,a_a000019,7,송도달빛축제공원,2022-08-06,2022-08-06,인천 연수구 센트럴로 350,인천 연수구 송도동 26-1,126.634896,37.407218,...,5.0,3.0,서울특별시,인천,3인 이상 여행(가족 외),2022-08-06~2022-08-07,7.0,5.0,1.0,6.0
30153,2209060002,a_a000567,2,콩카페 롯데백화점 잠실점,2022-09-06,2022-09-06,서울 송파구 올림픽로 240,서울 송파구 잠실동 40-1,127.098572,37.511906,...,2.0,7.0,경기도,경기,2인 여행(가족 외),2022-09-06~2022-09-07,5.0,2.0,3.0,1.0

In [10]:
df[df['TRAVEL_ID'] == 'a_a015688']

,VISIT_AREA_ID,TRAVEL_ID,VISIT_ORDER,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,LOTNO_ADDR,X_COORD,Y_COORD,...,TRAVEL_STYL_7,TRAVEL_STYL_8,TRAVEL_STATUS_RESIDENCE,TRAVEL_STATUS_DESTINATION,TRAVEL_STATUS_ACCOMPANY,TRAVEL_STATUS_YMD,TRAVEL_MOTIVE_1,TRAVEL_MOTIVE_2,TRAVEL_MOTIVE_3,TRAVEL_COMPANIONS_NUM
0,2210300006,a_a015688,5,프로방스마을,2022-10-30,2022-10-30,경기 파주시 탄현면 새오리로 77,경기 파주시 탄현면 성동리 82-1,126.685239,37.790405,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0
7060,2210300002,a_a015688,7,다온무인텔,2022-10-30,2022-10-31,경기 파주시 탄현면 성동로 7-25,경기 파주시 탄현면 성동리 666-3,126.686597,37.780606,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0
8788,2210300005,a_a015688,4,헤이리예술마을,2022-10-30,2022-10-30,NaN,경기 파주시 탄현면 법흥리 1652-239,126.698953,37.788174,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0
10467,2210310002,a_a015688,9,집,2022-10-31,2022-11-01,NaN,NaN,NaN,NaN,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0
13659,2210310001,a_a015688,8,아이노스 출판단지점,2022-10-31,2022-10-31,경기 파주시 문발로 142,경기 파주시 문발동 531-1,126.686457,37.707170,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0
18718,2210300004,a_a015688,3,롯데프리미엄아울렛 파주점,2022-10-30,2022-10-30,경기 파주시 문발로 284,경기 파주시 문발동 644,126.692643,37.718115,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0
28239,2210300003,a_a015688,2,지혜의숲,2022-10-30,2022-10-30,경기 파주시 회동길 145,경기 파주시 문발동 524-3,126.687060,37.708354,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0